# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_server import identity_pb2 as identity__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub(object):
    """Internal service used by OTHER McCain platform microservices to verify
    JWTs issued by this identity service, without each of them needing the
    JWT secret or re-implementing token logic. Kept as gRPC (not REST)
    because this is a high-frequency, low-latency, service-to-service call
    that sits on the hot path of every authenticated request in the platform.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyToken = channel.unary_unary(
                '/identity.IdentityService/VerifyToken',
                request_serializer=identity__pb2.VerifyTokenRequest.SerializeToString,
                response_deserializer=identity__pb2.VerifyTokenResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/identity.IdentityService/GetUser',
                request_serializer=identity__pb2.GetUserRequest.SerializeToString,
                response_deserializer=identity__pb2.GetUserResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer(object):
    """Internal service used by OTHER McCain platform microservices to verify
    JWTs issued by this identity service, without each of them needing the
    JWT secret or re-implementing token logic. Kept as gRPC (not REST)
    because this is a high-frequency, low-latency, service-to-service call
    that sits on the hot path of every authenticated request in the platform.
    """

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=identity__pb2.VerifyTokenRequest.FromString,
                    response_serializer=identity__pb2.VerifyTokenResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=identity__pb2.GetUserRequest.FromString,
                    response_serializer=identity__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identity.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identity.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """Internal service used by OTHER McCain platform microservices to verify
    JWTs issued by this identity service, without each of them needing the
    JWT secret or re-implementing token logic. Kept as gRPC (not REST)
    because this is a high-frequency, low-latency, service-to-service call
    that sits on the hot path of every authenticated request in the platform.
    """

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/VerifyToken',
            identity__pb2.VerifyTokenRequest.SerializeToString,
            identity__pb2.VerifyTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/GetUser',
            identity__pb2.GetUserRequest.SerializeToString,
            identity__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
